
name: publish-factors
on:
  workflow_dispatch:
  push:
    paths:
      - 'fetchers/**'
      - 'pipelines/**'
      - 'tools/**'
      - '.github/workflows/publish-factors.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy requests beautifulsoup4 yfinance html5lib lxml
      - name: Ensure packages
        run: |
          mkdir -p data/raw docs models fetchers pipelines tools
      - name: Compose factors_namm50.json (minimal)
        run: |
          python - << 'PY'
          import json, os, pandas as pd
          as_of = pd.Timestamp.utcnow().isoformat()+"Z"
          out = {"as_of":as_of, "factors":{}}
          os.makedirs("docs", exist_ok=True)
          with open("docs/factors_namm50.json","w") as f: json.dump(out, f)
          print("wrote docs/factors_namm50.json")
          PY
      - name: Commit docs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/factors_namm50.json || true
          git commit -m "Update factors_namm50 [skip ci]" || echo "no changes"
          git push
