name: publish-backtests
on:
  push:
    branches: [ "main" ]
    paths:
      - "backtest_runner.py"
      - ".github/workflows/publish-backtests.yml"
      - "requirements.txt"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}
      ALPHAVANTAGE_API_KEY: ${{ secrets.ALPHAVANTAGE_API_KEY }}
      AM_SYMBOLS: ${{ vars.AM_SYMBOLS }}
      AM_START: ${{ vars.AM_START }}
      AM_VERSION: ${{ vars.AM_VERSION }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run backtest
        run: |
          set -e
          if [ -f backtest_runner.py ]; then             python backtest_runner.py               --start "${{ env.AM_START || '2015-01-01' }}"               --version "${{ env.AM_VERSION || 'v1.6.1' }}"               --out ./docs/backtests.json               --registry ./docs/am_registry.json               --symbols "${{ env.AM_SYMBOLS || 'TQQQ,SOXL' }}";           else             echo "backtest_runner.py not found, skip.";           fi
      - name: Commit & push
        run: |
          set -e
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/backtests.json docs/am_registry.json || true
          if git diff --cached --quiet; then
            echo "No backtest changes"
          else
            git commit -m "Update backtests (auto)"
            git push
          fi
