name: publish-factors

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - "fetchers/**"
      - "pipelines/**"
      - "tools/**"
      - ".github/workflows/publish-factors.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        shell: bash
        run: |
          python -V
          python -m pip install -U pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else:
            pip install requests pandas beautifulsoup4 lxml html5lib yfinance
          fi

      - name: Ensure packages
        run: |
          mkdir -p fetchers pipelines tools seed docs data/raw
          touch fetchers/__init__.py pipelines/__init__.py tools/__init__.py

      - name: Fetch NAAIM (robust)
        env:
          NAAIM_MIRROR_URLS: ${{ vars.NAAIM_MIRROR_URLS }}
        run: |
          python fetchers/naaim.py || true

      - name: Compose factors_namm50.json (fallback if pipeline missing)
        shell: bash
        run: |
          python - << 'PY'
          import os, json, pandas as pd
          out_json = 'docs/factors_namm50.json'
          csv = 'data/raw/naaim_exposure.csv'
          os.makedirs(os.path.dirname(out_json), exist_ok=True)
          if os.path.exists(csv):
              df = pd.read_csv(csv).dropna()
              # infer columns
              date_col = 'date' if 'date' in df.columns else [c for c in df.columns if 'date' in c.lower()][0]
              val_cands = [c for c in df.columns if c.lower() in ('value','exposure','naaim')]
              val_col = val_cands[0] if val_cands else df.columns[-1]
              series = [[str(pd.to_datetime(d).date()), None, float(v)] for d, v in zip(df[date_col], df[val_col]) if pd.notna(v)]
          else:
              series = None
          payload = {
              "as_of": pd.Timestamp.utcnow().strftime("%Y-%m-%dT%H:%M:%S+00:00"),
              "factors": {
                  "naaim_exposure": {"series": series},
                  "fred_macro": {"series": None},
                  "ndx_breadth": {"series": None},
                  "china_proxy": {"series": None}
              }
          }
          with open(out_json, 'w') as f:
              json.dump(payload, f, ensure_ascii=False)
          print(f"wrote {out_json}, rows={0 if series is None else len(series)}")
          PY

      - name: Commit factors
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/factors_namm50.json data/raw/naaim_exposure.csv || true
          git commit -m "Update factors (NAAIM + compose) [skip ci]" || echo "nothing to commit"
