
name: train-models

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install numpy pandas
      - name: Train NAMM-50
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          python models/namm50/train.py
      - name: Commit model/backtests
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/models/namm50.json || true
          git commit -m "Publish NAMM-50 model [skip ci]" || echo "no model changes"
          git push
