
name: train-models
on:
  workflow_dispatch:
  schedule:
    - cron: '45 22 * * 1-5'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy requests
      - name: Train NAMM-50
        run: |
          python models/namm50/train.py
      - name: Commit model/backtests
        run: |
          git config user.name github-actions
          git config user.email actions@github.com
          git add docs/models/*.json docs/backtests.json data/models/namm50/*.csv || true
          git commit -m "Train models [skip ci]" || echo "No changes"
          git push
