name: train-models-lite

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * 1-5'  # weekdays 08:00 UTC

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: .
      ALPHAVANTAGE_API_KEY: ${{ secrets.ALPHAVANTAGE_API_KEY }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install --no-input requests pandas numpy python-dateutil yfinance

      - name: Train NAMM-50 (free / lite)
        run: |
          if [ -f models/namm50/train.py ]; then python models/namm50/train.py; else python -m models.namm50.train || true; fi

      - name: Ensure model JSON published
        run: |
          mkdir -p docs/models
          if [ -f models/docs/models/namm50.json ]; then cp -f models/docs/models/namm50.json docs/models/namm50.json; fi

      - name: Commit model/backtests (lite)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git pull --rebase origin "${GITHUB_REF_NAME}" || true
          git add docs/models || true
          git commit -m "Publish NAMM-50 model (lite) [skip ci]" || echo "nothing to commit"
          git push || echo "nothing to push"