name: publish-prices

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 13-21 * * 1-5'   # 每30分钟（美股交易时段 UTC 13–21）
  push:
    paths:
      - 'fetchers/prices.py'
      - '.github/workflows/publish-prices.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: Fetch prices
        env:
          ALPHAVANTAGE_API_KEY: ${{ secrets.ALPHAVANTAGE_API_KEY }}
        run: python fetchers/prices.py
      - name: Commit prices.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/prices.json
          git commit -m "Update prices.json [skip ci]" || echo "No changes"
          git push
