name: publish-factors
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - "fetchers/**"
      - "models/**"
      - "pipelines/**"
      - "tools/**"
      - ".github/workflows/publish-factors.yml"
      - "requirements.txt"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}
      FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
      NASDAQ_API_KEY: ${{ secrets.NASDAQ_API_KEY }}
      ALPHAVANTAGE_API_KEY: ${{ secrets.ALPHAVANTAGE_API_KEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Fetch data
        run: |
          set -e
          if [ -f fetchers/naaim.py ]; then python fetchers/naaim.py; fi
          if [ -f fetchers/ndx_breadth.py ]; then python fetchers/ndx_breadth.py; fi
          if [ -f fetchers/china50.py ]; then python fetchers/china50.py; fi
          if [ -f fetchers/fred_namm50.py ]; then python fetchers/fred_namm50.py; fi
      - name: Train NAMM-50
        run: |
          set -e
          if [ -f models/namm50/train.py ]; then python models/namm50/train.py; fi
      - name: Compose outputs
        run: |
          set -e
          if [ -f pipelines/compose_outputs.py ]; then python pipelines/compose_outputs.py; fi
      - name: Commit & push
        run: |
          set -e
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/*.json || true
          if git diff --cached --quiet; then
            echo "No JSON changes"
          else
            git commit -m "Update factors/backtests (auto)"
            git push
          fi
