name: publish-factors

on:
  workflow_dispatch:
  push:
    paths:
      - 'fetchers/**'
      - 'pipelines/**'
      - '.github/workflows/publish-factors.yml'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: .

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install --no-input requests pandas numpy python-dateutil yfinance beautifulsoup4 lxml peewee websockets tzdata

      - name: Ensure packages
        run: |
          mkdir -p fetchers pipelines tools models data/raw core docs

      - name: Fetch NAAIM (robust)
        run: |
          if [ -f fetchers/naaim.py ]; then python fetchers/naaim.py || true; fi

      - name: Compose factors_namm50.json (minimal)
        run: |
          if [ -f pipelines/compose_outputs.py ]; then python -m pipelines.compose_outputs; else echo "compose script missing, skip"; fi

      - name: Commit docs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          # 防止非 fast-forward 导致的 push 失败
          git pull --rebase origin "${GITHUB_REF_NAME}" || true
          git add docs || true
          git commit -m "Update factors_namm50 [skip ci]" || echo "nothing to commit"
          git push || echo "nothing to push"