name: publish-factors
on:
  workflow_dispatch:
  push:
    paths:
      - 'fetchers/**'
      - 'pipelines/**'
      - 'tools/**'
      - '.github/workflows/publish-factors.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Ensure package init files
        run: |
          mkdir -p fetchers pipelines tools models namm50 signals
          touch fetchers/__init__.py pipelines/__init__.py tools/__init__.py models/__init__.py namm50/__init__.py signals/__init__.py
      - name: Run factor pipelines (package mode)
        env:
          PYTHONPATH: ${{ github.workspace }}
          FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
          NASDAQ_API_KEY: ${{ secrets.NASDAQ_API_KEY }}
          ALPHAVANTAGE_API_KEY: ${{ secrets.ALPHAVANTAGE_API_KEY }}
        run: |
          python -m fetchers.naaim
          python -m pipelines.fetch_ndx_breadth || true
          python -m pipelines.fetch_china50 || true
          python -m pipelines.fetch_fred_namm50
          python -m pipelines.compose_outputs
      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "publish-factors: package mode hotfix [skip ci]"
            git push
          fi
