
name: publish-prices

on:
  workflow_dispatch:
  schedule:
    - cron: "0 20 * * 1-5"   # daily weekdays 20:00 UTC
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          pip install --upgrade pip
          pip install requests pandas python-dateutil
      - name: Fetch prices
        env:
          ALPHAVANTAGE_API_KEY: ${{ secrets.ALPHAVANTAGE_API_KEY }}
          PYTHONPATH: ${{ github.workspace }}
        run: |
          python fetchers/prices.py
      - name: Commit prices.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/prices.json || true
          git commit -m "Update prices.json [skip ci]" || echo "no price changes"
          git push
