name: train-models
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Ensure package init files
        run: |
          mkdir -p fetchers pipelines tools models namm50 signals
          touch fetchers/__init__.py pipelines/__init__.py tools/__init__.py models/__init__.py namm50/__init__.py signals/__init__.py
      - name: Train NAMM-50 (package mode)
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          python -m models.namm50.train
      - name: Commit model/backtests
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "train-models: outputs [skip ci]"
            git push
          fi
