name: train-models

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true

      - name: Ensure packages
        run: |
          mkdir -p models namm50 tools docs
          touch models/__init__.py namm50/__init__.py tools/__init__.py

      - name: Train NAMM-50
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          python - <<'PY'
          import os, runpy
          os.environ.setdefault("PYTHONPATH", os.getcwd())
          runpy.run_module("models.namm50.train", run_name="__main__")
          PY

      - name: Commit model/backtests
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/*.json || true
          if git diff --cached --quiet; then
            echo "no changes"
          else
            git commit -m "Update NAMM-50 model outputs [skip ci]" || true
            git push
          fi
