
    name: train-models

    on:
      workflow_dispatch:

    permissions:
      contents: write

    jobs:
      build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
            with: { fetch-depth: 0 }
          - uses: actions/setup-python@v5
            with: { python-version: '3.11' }
          - name: Install deps
            run: |
              python -m pip install -U pip
              pip install pandas numpy peewee openpyxl python-dateutil requests beautifulsoup4 lxml
          - name: Train NAMM-50 (free)
            run: |
              python -m models.namm50.train

- name: Commit docs
  run: |
    git config user.name "github-actions[bot]"
    git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
    git fetch origin main
    git pull --rebase origin main
    git add docs/**/*.json || true
    git add docs/*.json || true
    git add docs/models/*.json || true
    git commit -m "Update docs [hotfix path/core] [skip ci]" || echo "no changes"
    git push origin HEAD:main

