name: publish-prices
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy yfinance
      - name: Fetch prices
        run: python fetchers/prices.py
      - name: Commit prices.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/prices.json
          git commit -m "Update prices pack [skip ci]" || echo "no changes"
          git push
