name: publish-factors

on:
  workflow_dispatch:
  schedule:
    - cron: '15 10 * * 2-6'   # Tue-Sat 10:15 UTC ~= 03:15 PT (after US close)

permissions:
  contents: write
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ensure packages & dirs
        run: |
          mkdir -p fetchers pipelines tools models namn50 signals docs data/raw

      - name: Fetch data
        env:
          FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
          NASDAQ_API_KEY: ${{ secrets.NASDAQ_API_KEY }}
        run: |
          python - <<'PY'
          import os, sys
          from pathlib import Path
          sys.path.insert(0, str(Path(__file__).resolve().parents[2]))
          print("[run] fetchers.naaim"); import fetchers.naaim as NAAIM; NAAIM.main()
          print("[run] pipelines.fetch_ndx_breadth"); import pipelines.fetch_ndx_breadth as B; 
          try: B.main()
          except Exception as e: print("Breadth empty; keep previous file.", e)
          print("[run] pipelines.fetch_china50"); import pipelines.fetch_china50 as C; 
          try: C.main()
          except Exception as e: print("china50 empty; wrote placeholder.", e)
          print("[run] pipelines.fetch_fred_namm50"); import pipelines.fetch_fred_namm50 as F; F.main()
          PY

      - name: Compose outputs
        run: |
          python - <<'PY'
          import os, sys
          from pathlib import Path
          sys.path.insert(0, str(Path(__file__).resolve().parents[2]))
          print("[run] pipelines.compose_outputs"); import pipelines.compose_outputs as CO; CO.main()
          PY

      - name: Commit docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/*.json data/raw/*.csv 2>/dev/null || true
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git commit -m "Update NAMM-50 factors & overlays [skip ci]"
          # Ensure remote uses token
          git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          git push origin "${GITHUB_REF}"
