name: publish-factors
on:
  workflow_dispatch:
  schedule:
    - cron: "5 10 * * 2-6"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy yfinance requests pyyaml
      - name: Fetch data
        run: |
          python fetchers/naaim.py || true
          python fetchers/fred_bundle.py || true
          python fetchers/ndx_breadth_topn.py || true
          python fetchers/china_proxy_fxi.py || true
          python fetchers/prices.py || true
      - name: Compose outputs
        run: python pipelines/compose_outputs.py
      - name: Build signals
        run: python - <<'PY'
from models.namm50.signal import main
main()
PY
      - name: Build playbook
        run: python - <<'PY'
from models.namm50.playbook import main
main()
PY
      - name: Commit docs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/factors_namm50.json docs/signals_namm50.json docs/playbook_namm50.json
          git commit -m "Update NAMM-50 factors & signals [skip ci]" || echo "no changes"
          git push
