
name: publish-prices
on:
  workflow_dispatch:
  schedule:
    - cron: '5 21 * * 1-5'
  push:
    paths:
      - 'fetchers/prices.py'
      - '.github/workflows/publish-prices.yml'
env:
  PRICES_TICKERS: SPY,QQQ,TQQQ
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy requests yfinance
      - name: Fetch prices
        run: |
          python fetchers/prices.py
      - name: Commit prices.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          BRANCH="${GITHUB_REF##*/}"
          git pull --rebase origin "$BRANCH"
          git add docs/prices.json || true
          git commit -m "Update prices.json [skip ci]" || echo "no changes"
          git pull --rebase origin "$BRANCH"
          git push origin HEAD:"$BRANCH" || (git pull --rebase origin "$BRANCH" && git push origin HEAD:"$BRANCH")
