
name: publish-prices

on:
  schedule:
    - cron: "20 * * * 1-5"  # 每工作日整点 +20 分跑一次
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Fetch prices
        env:
          ALPHAVANTAGE_API_KEY: ${{ secrets.ALPHAVANTAGE_API_KEY }}
        run: |
          python fetchers/prices.py

      - name: Commit prices.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/prices.json || true
          git commit -m "Update prices.json [skip ci]" || echo "no changes"
          git push
