name: Publish Backtests
on:
  schedule:
    - cron: '20 1 * * 2-6'
  workflow_dispatch:
  push:
    paths:
      - backtest_runner.py
      - requirements.txt
      - .github/workflows/publish-backtests.yml
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run backtest
        env:
          ALPHAVANTAGE_API_KEY: ${{ secrets.ALPHAVANTAGE_API_KEY }}
          AM_SYMBOLS: ${{ vars.AM_SYMBOLS }}
          AM_START: ${{ vars.AM_START }}
          AM_VERSION: ${{ vars.AM_VERSION }}
        run: |
          python backtest_runner.py \
            --start "${AM_START:-2015-01-01}" \
            --version "${AM_VERSION:-v1.6.1}" \
            --out ./docs/backtests.json \
            --registry ./docs/am_registry.json \
            --symbols "${AM_SYMBOLS:-TQQQ,SOXL}"
      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/backtests.json docs/am_registry.json || true
          if git diff --cached --quiet; then
            echo "No changes"
          else
            git commit -m "Update backtests [skip ci]"
            git push
          fi
